GET http://localhost:8080/student

###
POST http://localhost:8080/student
Content-Type: application/json

{
  "name": "Romka",
  "gender": "male",
  "email": "romka@email.com",
  "id": 2,
  "dob": "2006-06-09"
}